import { User, Applicant, CounselingSession, Introduction, Task, AuditLog } from './types';
import { calculateAgeFromJalali, parseJalaliDate, CURRENT_SOLAR_YEAR } from './utils/persianDate';

export const INITIAL_USERS: User[] = [
  {
    id: 'user_admin',
    name: 'مهندس محمدرضا شریفی',
    email: 'admin@alzahra-crm.ir',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    role: 'main_admin',
    roleTitle: 'مدیر ارشد و سیاست‌گذار مرکز',
    phone: '۰۹۱۲۱۱۱۰۰۰۰',
    department: 'ریاست و نظارت عالیه',
    assignedCount: 0,
  },
  {
    id: 'user_manager',
    name: 'سرکار خانم دکتر حسینی',
    email: 'manager@alzahra-crm.ir',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    role: 'internal_manager',
    roleTitle: 'مدیر داخلی و اجرایی',
    phone: '۰۹۱۲۲۲۲۰۰۰۰',
    department: 'مدیریت فرایندها و پرسنل',
    assignedCount: 140,
  },
  {
    id: 'user_employee',
    name: 'خانم سمیه ناصری',
    email: 'naseri@alzahra-crm.ir',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    role: 'employee',
    roleTitle: 'کارشناس ارشد پذیرش و تطبیق',
    phone: '۰۹۱۲۳۳۳۰۰۰۰',
    department: 'واحد تطبیق و هماهنگی',
    assignedCount: 45,
  },
  {
    id: 'user_counselor',
    name: 'دکتر علیرضا رمضانی',
    email: 'dr.ramezani@alzahra-crm.ir',
    avatar: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=150&auto=format&fit=crop&q=80',
    role: 'counselor',
    roleTitle: 'مشاور ارشد ازدواج و روانشناس',
    phone: '۰۹۱۲۴۴۴۰۰۰۰',
    department: 'کلینیک مشاوره پیش از ازدواج',
    assignedCount: 28,
  },
  {
    id: 'user_applicant',
    name: 'علی کریمی (مراجع نمونه)',
    email: 'applicant@alzahra-crm.ir',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    role: 'applicant',
    roleTitle: 'مراجع / متقاضی همسان‌گزینی',
    phone: '۰۹۱۲۵۵۵۰۰۰۰',
    department: 'پورتال متقاضیان',
    assignedCount: 0,
  },
];

// Helper to ensure full database standard fields
export const buildApplicant = (raw: any): Applicant => {
  const caseCode = raw.caseCode || raw.fileCode?.replace('#', '') || '10001';
  const fileCode = raw.fileCode || (raw.caseCode ? (raw.caseCode.startsWith('#') ? raw.caseCode : `#${raw.caseCode}`) : `#${caseCode}`);
  const gender = raw.gender || 'male';
  const age = raw.age || 30;
  const isMale = gender === 'male';

  const maritalHistory = raw.maritalHistory && typeof raw.maritalHistory === 'object' && raw.maritalHistory.previousMarriageStatus
    ? raw.maritalHistory
    : {
        previousMarriageStatus: (raw.maritalHistory === 'divorced' ? 'divorced' : raw.maritalHistory === 'widowed' ? 'widowed' : 'never_married') as any,
        previousMarriageStatusFa: raw.maritalHistory === 'divorced' ? 'متأهل سابق (جدا شده)' : raw.maritalHistory === 'widowed' ? 'همسر فوت‌شده' : 'مجرد (فاقد سابقه ازدواج)',
        marriageDurationMonths: raw.maritalHistory === 'divorced' ? 24 : 0,
        marriageDurationText: raw.maritalHistory === 'divorced' ? '۲ سال زندگی مشترک' : 'فاقد سابقه زندگی مشترک',
        separationDate: raw.maritalHistory === 'divorced' ? '۱۳۹۹/۰۶/۱۵' : '',
        separationReason: raw.maritalHistory === 'divorced' ? 'عدم تفاهم فرهنگی و عدم تناسب خانوادگی' : '',
        childrenCount: raw.personalInfo?.childrenCount || 0,
        childrenCustodyStatus: raw.personalInfo?.childrenCount ? 'فرزند با مادر زندگی می‌کند' : 'ندارد',
      };

  const healthLifestyle = raw.healthLifestyle || {
    healthStatus: raw.personalInfo?.healthStatus || 'سالم و بدون بیماری مزمن',
    smokingStatus: (raw.lifestyle?.smoking ? 'smoker' : 'none') as any,
    smokingStatusFa: raw.lifestyle?.smoking ? 'مصرف دخانیات' : 'فاقد هرگونه مصرف دخانیات',
    lifestyleNotes: raw.lifestyle?.dietaryNotes || 'ورزش منظم، تغذیه سالم، اهل سفر و مطالعه',
    exerciseLevel: raw.lifestyle?.exerciseLevel || 'regular',
    travelInterest: raw.lifestyle?.travelInterest || 'high',
  };

  const educationSkills = raw.educationSkills || {
    academicEducation: raw.educationJob?.educationLevel || 'master',
    academicEducationFa: raw.educationJob?.educationLevelFa || 'کارشناسی ارشد',
    fieldOfStudy: raw.educationJob?.fieldOfStudy || 'مهندسی',
    university: raw.educationJob?.university || 'دانشگاه دولتی تهران',
    religiousEducation: raw.religiousEducation || 'ندارد (مطالعات آزاد معارفی)',
    additionalSkills: raw.additionalSkills || ['زبان انگلیسی پیشرفته', 'مدیریت و ارتباط موثر', 'تحلیل داده'],
  };

  const careerFinancial = raw.careerFinancial || {
    militaryStatus: isMale ? (raw.personalInfo?.militaryService || 'completed') : 'na',
    militaryStatusFa: isMale ? (raw.personalInfo?.militaryService === 'exempt_medical' ? 'معافیت پزشکی' : 'کارت پایان خدمت') : 'نامربوط',
    currentJob: raw.educationJob?.jobTitle || 'کارشناس ارشد',
    organizationType: raw.educationJob?.organizationType || 'private',
    incomeRange: raw.educationJob?.monthlyIncomeRange || '۳۵ تا ۵۰ میلیون تومان',
    insuranceStatus: 'social_security' as any,
    insuranceStatusFa: 'تأمین اجتماعی و بیمه تکمیلی',
    housingStatus: raw.personalInfo?.housingStatus || 'owner',
    housingStatusFa: raw.personalInfo?.housingStatus === 'owner' ? 'مالک مسکن' : raw.personalInfo?.housingStatus === 'tenant' ? 'مستأجر' : 'سکونت با خانواده',
    vehicleStatus: (raw.educationJob?.hasPersonalCar ? 'has_car' : 'none') as any,
    vehicleStatusFa: raw.educationJob?.hasPersonalCar ? 'دارای خودروی شخصی' : 'فاقد خودرو',
    financialIndependence: raw.educationJob?.financialIndependence ?? true,
  };

  const religiousValues = raw.religiousValues || {
    religion: 'اسلام',
    denomination: 'شیعه ۱۲ امامی',
    marja: raw.marja || 'آیت‌الله خامنه‌ای',
    prayerStatus: (raw.religionValues?.prayerCommitment === 'strict' ? 'strict_on_time' : 'regular') as any,
    prayerStatusFa: raw.religionValues?.prayerCommitment === 'strict' ? 'مقید به نماز اول وقت' : 'مرتب و اهل نماز',
    fastingStatus: 'strict' as any,
    fastingStatusFa: 'مقید به روزه کامل ماه مبارک رمضان',
    khumsStatus: 'committed_has_year' as any,
    khumsStatusFa: 'مقید و دارای حساب سال خمسی',
    personalCovering: (raw.religionValues?.hijabPreference || (isMale ? 'formal_suit' : 'chador_complete')) as any,
    personalCoveringFa: isMale ? 'پوشش رسمی و آراسته' : (raw.religionValues?.hijabPreference === 'manteau_modest' ? 'مانتویی موقر و باحجاب' : 'چادر کامل'),
    familyCovering: raw.familyCovering || 'چادر و پوشش کامل مذهبی',
    coreValues: raw.religionValues?.corePrinciples || ['صداقت', 'کسب روزی حلال', 'احترام به والدین', 'تقوا'],
  };

  const familyInfo = {
    fatherLiving: raw.familyInfo?.fatherLiving ?? true,
    fatherAge: raw.familyInfo?.fatherAge || 62,
    fatherJob: raw.familyInfo?.fatherJob || 'کارمند بازنشسته',
    fatherEducation: raw.familyInfo?.fatherEducation || 'کارشناسی',
    motherLiving: raw.familyInfo?.motherLiving ?? true,
    motherAge: raw.familyInfo?.motherAge || 58,
    motherJob: raw.familyInfo?.motherJob || 'خانه‌دار / فرهنگی',
    motherEducation: raw.familyInfo?.motherEducation || 'دیپلم',
    parentsMaritalStatus: raw.familyInfo?.parentsMaritalStatus || 'living_together' as any,
    parentsMaritalStatusFa: raw.familyInfo?.parentsMaritalStatusFa || 'در حال زندگی مشترک',
    sistersCountAndStatus: raw.familyInfo?.sistersCountAndStatus || '۱ خواهر متأهل',
    brothersCountAndStatus: raw.familyInfo?.brothersCountAndStatus || '۱ برادر مجرد دانشجو',
    livingWith: raw.familyInfo?.livingWith || (careerFinancial.housingStatus === 'owner' ? 'مستقل در مسکن شخصی' : 'همراه با والدین'),
    birthOrder: raw.familyInfo?.birthOrder || 1,
    familyCultureType: raw.familyInfo?.familyCultureType || 'moderate',
    economicLevel: raw.familyInfo?.economicLevel || 'upper_middle',
    counselorFamilyNotes: raw.familyInfo?.counselorFamilyNotes || 'خانواده محترم، اصیل و دارای فرهنگ والای گفتگوی خانوادگی.',
  };

  const personality = {
    mbti: raw.personality?.mbti || 'INTJ',
    mbtiTitleFa: raw.personality?.mbtiTitleFa || 'تحلیل‌گر و باهدف',
    attachmentStyle: raw.personality?.attachmentStyle || 'ایمن',
    personalityTraits: raw.personality?.personalityTraits || raw.personality?.keyTraits || ['منطقی', 'مسئولیت‌پذیر', 'صادق', 'متعهد'],
    keyTraits: raw.personality?.keyTraits || raw.personality?.personalityTraits || ['منطقی', 'مسئولیت‌پذیر', 'صادق', 'متعهد'],
    strengths: raw.personality?.strengths || ['ثبات هیجانی بالا', 'روابط اجتماعی سالم', 'مدیریت استرس'],
    personalityNotes: raw.personality?.personalityNotes || raw.personality?.counselorImpression || 'شخصیتی بسیار پخته، آماده تشکیل خانواده پایدار و دارای سلامت روان ارزیابی‌شده.',
    counselorImpression: raw.personality?.counselorImpression || raw.personality?.personalityNotes || 'شخصیتی بسیار پخته، آماده تشکیل خانواده پایدار و دارای سلامت روان ارزیابی‌شده.',
    bigFive: raw.personality?.bigFive || { conscientiousness: 80, extraversion: 60, agreeableness: 75, neuroticism: 25, openness: 75 },
  };

  const marriagePreferences = {
    preferredPartnerCriteria: raw.marriagePreferences?.preferredPartnerCriteria || raw.marriagePreferences?.corePriorities || ['پایبندی اخلاقی و ایمانی', 'تحصیلات متناسب', 'خانواده اصیل و آرام'],
    ageMin: raw.marriagePreferences?.ageMin || (isMale ? age - 6 : age),
    ageMax: raw.marriagePreferences?.ageMax || (isMale ? age : age + 6),
    heightMin: raw.marriagePreferences?.heightMin || (isMale ? 160 : 175),
    heightMax: raw.marriagePreferences?.heightMax || (isMale ? 175 : 190),
    acceptableCities: raw.marriagePreferences?.acceptableCities || ['تهران', 'قم', 'کرج', 'اصفهان'],
    minEducation: raw.marriagePreferences?.minEducation || 'کارشناسی',
    acceptableMaritalHistory: raw.marriagePreferences?.acceptableMaritalHistory || ['never_married'],
    importantValues: raw.marriagePreferences?.importantValues || raw.marriagePreferences?.corePriorities || ['صداقت', 'رشد اخلاقی', 'حفظ حریم خانواده'],
    priorities: raw.marriagePreferences?.priorities || raw.marriagePreferences?.corePriorities || ['تفاهم فکری', 'سلامت روان', 'پایبندی ایمانی'],
    dealBreakers: raw.marriagePreferences?.dealBreakers || ['دروغگویی', 'مصرف دخانیات', 'عدم پایبندی اخلاقی'],
    religiousExpectations: raw.marriagePreferences?.religiousExpectations || 'پایبند به مبانی اخلاقی و واجبات دینی',
    financialExpectations: raw.marriagePreferences?.financialExpectations || 'همراهی در رشد خانواده و درک متقابل شرایط اقتصادی',
  };

  // Safe backward-compatible legacy objects
  const religionValues = raw.religionValues || {
    religiousCommitment: (religiousValues.prayerStatus === 'strict_on_time' || religiousValues.prayerStatus === 'always_strict') ? 'high' : 'moderate',
    religiousCommitmentFa: religiousValues.prayerStatusFa || 'معتقد به واجبات و اخلاق‌مدار',
    prayerCommitment: (religiousValues.prayerStatus === 'strict_on_time' || religiousValues.prayerStatus === 'always_strict') ? 'strict' : 'regular',
    prayerCommitmentFa: religiousValues.prayerStatusFa || 'مرتب و اهل نماز',
    hijabPreference: religiousValues.personalCovering || (isMale ? 'formal_suit' : 'chador_complete'),
    hijabPreferenceFa: religiousValues.personalCoveringFa || (isMale ? 'پوشش رسمی و آراسته' : 'چادر کامل'),
    corePrinciples: religiousValues.coreValues || ['صداقت', 'کسب روزی حلال', 'احترام به والدین', 'تقوا'],
  };

  const educationJob = raw.educationJob || {
    educationLevel: educationSkills.academicEducation,
    educationLevelFa: educationSkills.academicEducationFa,
    fieldOfStudy: educationSkills.fieldOfStudy,
    university: educationSkills.university,
    jobTitle: careerFinancial.currentJob,
    occupation: careerFinancial.currentJob,
    organizationType: careerFinancial.organizationType,
    monthlyIncomeRange: careerFinancial.incomeRange,
    hasPersonalCar: careerFinancial.vehicleStatus === 'personal_car' || careerFinancial.vehicleStatus === 'has_car',
    financialIndependence: careerFinancial.financialIndependence ?? true,
  };

  const lifestyle = raw.lifestyle || {
    smoking: healthLifestyle.smokingStatus === 'smoker',
    smokingFa: healthLifestyle.smokingStatusFa,
    exerciseLevel: healthLifestyle.exerciseLevel,
    travelInterest: healthLifestyle.travelInterest,
    dietaryNotes: healthLifestyle.lifestyleNotes,
  };

  const personalInfo = raw.personalInfo || {
    height: raw.height || (isMale ? 180 : 165),
    weight: raw.weight || (isMale ? 78 : 58),
    housingStatus: careerFinancial.housingStatus,
    militaryService: careerFinancial.militaryStatus,
    healthStatus: healthLifestyle.healthStatus,
    childrenCount: maritalHistory.childrenCount || 0,
  };

  return {
    ...raw,
    id: raw.id || `app_${Math.floor(10000 + Math.random() * 90000)}`,
    caseCode,
    fileCode,
    category: raw.category || (raw.isVip ? 'VIP و نخبگان' : 'عادی'),
    registrationDate: raw.registrationDate || '۱۴۰۲/۰۸/۱۵',
    registrationMethod: raw.registrationMethod || 'in_person',
    lastUpdateDate: raw.lastUpdateDate || '۱۴۰۲/۰۹/۲۰',
    updateMethod: raw.updateMethod || 'in_person',
    workflowStatus: raw.workflowStatus || (raw.status === 'active' ? 'MATCHING' : raw.status === 'introduced' ? 'INTRODUCED' : 'COUNSELING'),
    status: raw.status || 'active',
    firstName: raw.firstName || 'متقاضی',
    lastName: raw.lastName || 'محترم',
    nationalId: raw.nationalId || '۰۰۱۲۳۴۵۶۷۸',
    phone: raw.phone || '۰۹۱۲-۳۴۵-۶۷۸۹',
    guardianPhone: raw.guardianPhone || '۰۹۱۲-۱۱۱-۲۲۲۲',
    gender,
    birthDate: raw.birthDate || `۱۳${String(CURRENT_SOLAR_YEAR - age).slice(2)}/۰۴/۱۵`,
    birthYear: raw.birthYear || (raw.birthDate ? parseJalaliDate(raw.birthDate)?.year || (CURRENT_SOLAR_YEAR - age) : (CURRENT_SOLAR_YEAR - age)),
    age: raw.birthDate ? calculateAgeFromJalali(raw.birthDate) : age,
    birthPlace: raw.birthPlace || 'تهران',
    residenceCity: raw.residenceCity || raw.city || 'تهران',
    province: raw.province || 'تهران',
    address: raw.address || 'تهران، منطقه ۲',
    nationalityOrigin: raw.nationalityOrigin || 'فارس / تهرانی اصیل',
    height: raw.height || personalInfo.height || (isMale ? 180 : 165),
    weight: raw.weight || personalInfo.weight || (isMale ? 78 : 58),
    maritalHistory,
    healthLifestyle,
    educationSkills,
    careerFinancial,
    religiousValues,
    familyInfo,
    personality,
    marriagePreferences,
    files: raw.files || [],
    // Legacy aliases
    religionValues,
    educationJob,
    lifestyle,
    personalInfo,
    city: raw.city || raw.residenceCity || 'تهران',
    lastUpdate: raw.lastUpdate || 'امروز، ۱۰:۳۰',
  };
};

const RAW_APPLICANTS = [
  {
    id: 'app_49821',
    fileCode: '۴۹۸۲۱#',
    caseCode: 'PR-49821',
    category: 'VIP و نخبگان',
    workflowStatus: 'MATCHING',
    registrationMethod: 'in_person',
    updateMethod: 'in_person',
    firstName: 'علیرضا',
    lastName: 'محمدی',
    gender: 'male',
    birthYear: 1370,
    birthDate: '۱۳۷۰/۰۸/۱۵',
    age: 32,
    birthPlace: 'تهران',
    residenceCity: 'تهران',
    nationalityOrigin: 'اصفهانی / تهرانی',
    province: 'تهران',
    address: 'تهران، سعادت آباد، خیابان سرو غربی',
    phone: '۰۹۱۲-۳۴۵-۶۷۸۹',
    guardianPhone: '۰۹۱۲-۱۱۱-۵۵۴۴',
    nationalId: '۰۰۱۲۳۴۵۶۷۸',
    status: 'active',
    registrationDate: '۱۴۰۲/۰۸/۱۵',
    lastUpdate: 'امروز، ۱۰:۳۰',
    isVip: true,
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    counselorId: 'user_counselor',
    counselorName: 'دکتر علیرضا رمضانی',
    assignedEmployeeId: 'user_employee',
    assignedEmployeeName: 'خانم سمیه ناصری',
    personalInfo: {
      height: 182,
      weight: 78,
      skinTone: 'گندم‌گون روشن',
      healthStatus: 'سالم و بدون سابقه بیماری خاص',
      specialConditions: 'بدون آلرژی یا محدودیت جسمی',
      militaryService: 'completed',
      maritalHistory: 'never_married',
      hasChildren: false,
      childrenCount: 0,
      housingStatus: 'owner',
    },
    familyInfo: {
      fatherLiving: true,
      fatherAge: 65,
      fatherJob: 'کارمند بازنشسته شرکت نفت',
      fatherEducation: 'کارشناسی ارشد مهندسی شیمی',
      motherLiving: true,
      motherAge: 60,
      motherJob: 'خانه‌دار و فعال خیریه',
      motherEducation: 'کارشناسی علوم تربیتی',
      siblingsCount: 1,
      sistersCountAndStatus: 'ندارد',
      brothersCountAndStatus: '۱ برادر کوچکتر (مجرد، دانشجوی کارشناسی ارشد)',
      livingWith: 'مستقل در آپارتمان شخصی (سعادت‌آباد)',
      birthOrder: 1,
      familyCultureType: 'moderate',
      economicLevel: 'upper_middle',
      counselorFamilyNotes: 'خانواده منسجم، تحصیل‌کرده و حمایت‌گر با پایبندی به اصول اخلاقی و اصالت فرهنگی.',
    },
    educationJob: {
      educationLevel: 'master',
      educationLevelFa: 'کارشناسی ارشد مهندسی صنایع',
      fieldOfStudy: 'مهندسی صنایع - مدیریت سیستم و بهره‌وری',
      university: 'دانشگاه صنعتی شریف',
      occupation: 'مدیر محصول ارشد شرکت نرم‌افزاری',
      jobTitle: 'مدیر محصول',
      organizationType: 'private',
      monthlyIncomeRange: '۶۰ تا ۸۰ میلیون تومان',
      financialIndependence: true,
      hasPersonalCar: true,
    },
    religiousEducation: 'ندارد (مطالعات شخصی در حوزه نهج‌البلاغه و اخلاق اسلامی)',
    additionalSkills: ['مدیریت پروژه حرفه‌ای (PMP)', 'طراحی سیستم‌ها', 'زبان انگلیسی تخصصی (IELTS 8)'],
    marja: 'آیت‌الله خامنه‌ای',
    lifestyle: {
      smoking: false,
      exerciseLevel: 'regular',
      dietaryNotes: 'رژیم غذایی متوازن و سالم',
      leisureActivities: ['کتابخوانی مدیریت و روانشناسی', 'کوهنوردی آخر هفته', 'طبیعت‌گردی و عکاسی', 'پادکست‌های علمی'],
      travelInterest: 'high',
      socialMediaUsage: 'moderate',
    },
    religionValues: {
      religiousCommitment: 'moderate',
      religiousCommitmentFa: 'معتقد به واجبات و اخلاق‌مدار',
      prayerCommitment: 'regular',
      hijabPreference: 'manteau_modest',
      hijabPreferenceFa: 'پوشش مانتویی موقر و آراسته یا چادر اختیاری',
      pilgrimageInterest: true,
      corePrinciples: ['صداقت و شفافیت کلامی', 'مسئولیت‌پذیری مالی و اخلاقی', 'حفظ حریم خانواده', 'گفتگوی منطقی در حل تعارض'],
    },
    personality: {
      mbti: 'INTJ',
      mbtiTitleFa: 'تحلیلگر و استراتژیک (معمار)',
      attachmentStyle: 'ایمن',
      bigFive: {
        conscientiousness: 85,
        extraversion: 40,
        agreeableness: 65,
        neuroticism: 25,
        openness: 80,
      },
      keyTraits: ['منطقی', 'مسئولیت‌پذیر', 'کمی درون‌گرا', 'هدف‌گرا', 'برنامه‌ریز دقیق', 'باثبات عاطفی'],
      counselorImpression: 'شخصیتی پخته، با توانایی عالی در حل مسئله و بینش عمیق. نیازمند همسری است که هوش کلامی و عاطفی بالا داشته و احترام به استقلال کاری را به رسمیت بشناسد.',
    },
    marriagePreferences: {
      ageMin: 24,
      ageMax: 30,
      heightMin: 162,
      heightMax: 175,
      acceptableCities: ['تهران', 'کرج'],
      minEducation: 'کارشناسی',
      acceptableMaritalHistory: ['never_married'],
      religiousExpectations: 'پایبند به مبانی اخلاقی و واجبات دینی با نگرش روشن‌بینانه',
      financialExpectations: 'همراهی در رشد خانواده، درک شرایط اقتصادی',
      preferredMbtiList: ['ENFP', 'ENTP', 'INFJ', 'ENFJ'],
      dealBreakers: ['دخالت بیش از حد بستگان', 'پنهان‌کاری مالی یا هویتی', 'مصرف دخانیات', 'بی‌هدفی شغلی و تحصیلی'],
      corePriorities: ['تناسب فکری و جهان‌بینی', 'درک متقابل احساسات', 'توسعه فردی طرفین', 'صداقت بی قید و شرط'],
    },
    files: [
      { id: 'f1', name: 'تصویر کارت ملی و شناسنامه.pdf', category: 'id_card', size: '۲.۴ مگابایت', uploadDate: '۱۴۰۲/۰۸/۱۵', url: '#', isConfidential: true },
      { id: 'f2', name: 'مدرک تحصیلی کارشناسی ارشد.pdf', category: 'education', size: '۱.۸ مگابایت', uploadDate: '۱۴۰۲/۰۸/۱۵', url: '#', isConfidential: false },
      { id: 'f3', name: 'گزارش آزمون NEO و MBTI.pdf', category: 'psych_test', size: '۳.۱ مگابایت', uploadDate: '۱۴۰۲/۰۸/۲۰', url: '#', isConfidential: true },
    ],
  },
  {
    id: 'app_519',
    fileCode: '۵۱۹#',
    firstName: 'سارا',
    lastName: 'محمدی (م.)',
    gender: 'female',
    birthYear: 1374,
    birthDate: '۱۳۷۴/۰۳/۲۲',
    age: 28,
    city: 'تهران',
    province: 'تهران',
    address: 'تهران، یوسف آباد، خیابان بیست و سوم',
    phone: '۰۹۱۲-۹۸۷-۶۵۴۳',
    nationalId: '۰۰۲۳۴۵۶۷۸۹',
    status: 'active',
    registrationDate: '۱۴۰۲/۰۹/۰۱',
    lastUpdate: 'امروز، ۰۹:۱۵',
    isVip: false,
    photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&auto=format&fit=crop&q=80',
    counselorId: 'user_counselor',
    counselorName: 'دکتر رمضانی',
    personalInfo: {
      height: 168,
      weight: 59,
      skinTone: 'سفید روشن',
      healthStatus: 'سالم و با نشاط',
      militaryService: 'na',
      maritalHistory: 'single',
      hasChildren: false,
      childrenCount: 0,
      housingStatus: 'living_with_family',
    },
    familyInfo: {
      fatherLiving: true,
      fatherAge: 62,
      fatherJob: 'استاد بازنشسته دانشگاه',
      motherLiving: true,
      motherAge: 57,
      motherJob: 'فرهنگی بازنشسته',
      siblingsCount: 2,
      siblingsOverview: '۱ خواهر بزرگتر (متاهل، داروساز) و ۱ برادر دانشجو',
      familyCultureType: 'moderate',
      economicLevel: 'upper_middle',
      counselorFamilyNotes: 'خانواده اهل علم، دارای روابط گرم و مشوق ابتکار و خلاقیت فرزندان.',
    },
    educationJob: {
      educationLevel: 'master',
      educationLevelFa: 'کارشناسی ارشد معماری داخلی',
      fieldOfStudy: 'معماری و طراحی فضاهای داخلی',
      university: 'دانشگاه هنر تهران',
      occupation: 'طراح ارشد در آتلیه معماری',
      jobTitle: 'معمار داخلی',
      organizationType: 'private',
      monthlyIncomeRange: '۳۵ تا ۵۰ میلیون تومان',
      financialIndependence: true,
      hasPersonalCar: true,
    },
    lifestyle: {
      smoking: false,
      exerciseLevel: 'regular',
      leisureActivities: ['نقاشی آبرنگ', 'طراحی فضاهای پایدار', 'کافه گردی آرام', 'سفرهای عکاسی معماری'],
      travelInterest: 'high',
      socialMediaUsage: 'moderate',
    },
    religionValues: {
      religiousCommitment: 'moderate',
      religiousCommitmentFa: 'معتقد به معنویت قلبی و اخلاق اجتماعی',
      prayerCommitment: 'regular',
      hijabPreference: 'manteau_modest',
      hijabPreferenceFa: 'مانتوی شیک، موقر و پوشیده',
      pilgrimageInterest: true,
      corePrinciples: ['همدلی و ابراز عواطف', 'احترام به حریم خصوصی', 'رشد و کمال دوجانبه', 'نشاط در محیط خانواده'],
    },
    personality: {
      mbti: 'ENFP',
      mbtiTitleFa: 'پیکارگر (شورمند و خلاق)',
      attachmentStyle: 'ایمن',
      bigFive: {
        conscientiousness: 72,
        extraversion: 78,
        agreeableness: 84,
        neuroticism: 32,
        openness: 92,
      },
      keyTraits: ['خلاق و پرانرژی', 'خوش‌برخورد و همدل', 'وفادار', 'انعطاف‌پذیر', 'هنردوست'],
      counselorImpression: 'شخصیتی بسیار پرمهر، با ذوق هنری و توانایی برقراری ارتباط موثر. تناسب بسیار خوبی با افراد منطقی و ساختاریافته (نظیر INTJ) دارد زیرا تعادل دلنشینی از نظم و نشاط پدید می‌آورد.',
    },
    marriagePreferences: {
      ageMin: 29,
      ageMax: 35,
      heightMin: 175,
      heightMax: 190,
      acceptableCities: ['تهران'],
      minEducation: 'کارشناسی',
      acceptableMaritalHistory: ['single'],
      religiousExpectations: 'اخلاق‌مدار، اهل حلال و حرام، احترام به عقاید',
      financialExpectations: 'استقلال مالی و توانایی اداره آبرومندانه زندگی',
      preferredMbtiList: ['INTJ', 'INFJ', 'ENTJ'],
      dealBreakers: ['تعصبات خشک و غیرمنطقی', 'سردی عاطفی مداوم', 'بدخلقی و پرخاشگری', 'دروغگویی'],
      corePriorities: ['ارتباط عاطفی عمیق', 'هنر و خلاقیت', 'سفرهای کوتاه', 'استقلال مالی دوطرفه'],
    },
    files: [
      { id: 'f4', name: 'مدرک کارشناسی ارشد معماری.pdf', category: 'education', size: '۲.۱ مگابایت', uploadDate: '۱۴۰۲/۰۹/۰۱', url: '#', isConfidential: false },
      { id: 'f5', name: 'پرسشنامه شخصیتی و سبک دلبستگی.pdf', category: 'psych_test', size: '۱.۶ مگابایت', uploadDate: '۱۴۰۲/۰۹/۰۵', url: '#', isConfidential: true },
    ],
  },
  {
    id: 'app_482',
    fileCode: '۴۸۲#',
    firstName: 'امیرحسین',
    lastName: 'رضایی (ر.)',
    gender: 'male',
    birthYear: 1370,
    birthDate: '۱۳۷۰/۰۵/۱۸',
    age: 32,
    city: 'تهران',
    province: 'تهران',
    address: 'تهران، پاسداران، بوستان ششم',
    phone: '۰۹۱۲-۱۱۱-۲۲۳۳',
    nationalId: '۰۰۱۴۵۶۷۸۹۰',
    status: 'active',
    registrationDate: '۱۴۰۲/۰۸/۰۲',
    lastUpdate: 'دیروز، ۱۶:۰۰',
    isVip: true,
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80',
    counselorId: 'user_counselor',
    counselorName: 'دکتر رمضانی',
    personalInfo: {
      height: 180,
      weight: 75,
      skinTone: 'سبزه روشن',
      healthStatus: 'عالی',
      militaryService: 'completed',
      maritalHistory: 'single',
      hasChildren: false,
      childrenCount: 0,
      housingStatus: 'owner',
    },
    familyInfo: {
      fatherLiving: true,
      fatherAge: 66,
      fatherJob: 'پزشک متخصص',
      motherLiving: true,
      motherAge: 61,
      motherJob: 'خانه‌دار',
      siblingsCount: 1,
      siblingsOverview: '۱ خواهر متاهل',
      familyCultureType: 'moderate',
      economicLevel: 'high',
      counselorFamilyNotes: 'خانواده اصیل، محترم و دارای پشتوانه قوی فرهنگی.',
    },
    educationJob: {
      educationLevel: 'master',
      educationLevelFa: 'کارشناسی ارشد مهندسی نرم‌افزار',
      fieldOfStudy: 'هوش مصنوعی و سیستم‌های توزیع‌شده',
      university: 'دانشگاه تهران',
      occupation: 'مهندس ارشد نرم‌افزار',
      jobTitle: 'مهندس نرم‌افزار',
      organizationType: 'private',
      monthlyIncomeRange: '۷۰ تا ۹۰ میلیون تومان',
      financialIndependence: true,
      hasPersonalCar: true,
    },
    lifestyle: {
      smoking: false,
      exerciseLevel: 'regular',
      leisureActivities: ['شنا', 'مطالعه فناوری و بیوگرافی', 'طراحی نرم‌افزارهای کاربردی'],
      travelInterest: 'moderate',
      socialMediaUsage: 'minimal',
    },
    religionValues: {
      religiousCommitment: 'moderate',
      religiousCommitmentFa: 'معتقد به واجبات و پایبند به اخلاق حرفه‌ای',
      prayerCommitment: 'regular',
      hijabPreference: 'manteau_modest',
      hijabPreferenceFa: 'پوشش محجوب و عرف جامعه',
      pilgrimageInterest: true,
      corePrinciples: ['مسئولیت‌پذیری', 'پیشرفت مداوم', 'پرهیز از حاشیه'],
    },
    personality: {
      mbti: 'INTJ',
      mbtiTitleFa: 'معمار و استراتژیست',
      attachmentStyle: 'ایمن',
      bigFive: {
        conscientiousness: 88,
        extraversion: 38,
        agreeableness: 68,
        neuroticism: 22,
        openness: 82,
      },
      keyTraits: ['هدفمند', 'منظم', 'وفادار', 'کم‌حرف اما عمیق'],
      counselorImpression: 'مردی متعهد، خوش‌فکر و بسیار قابل اتکا در مدیریت بحران و زندگی خانوادگی.',
    },
    marriagePreferences: {
      ageMin: 25,
      ageMax: 31,
      heightMin: 160,
      heightMax: 175,
      acceptableCities: ['تهران'],
      minEducation: 'کارشناسی',
      acceptableMaritalHistory: ['single'],
      religiousExpectations: 'همسو در اصول اخلاقی و سلامت روان',
      financialExpectations: 'عدم تجمل‌گرایی افراطی',
      preferredMbtiList: ['ENFP', 'ENTP', 'INFJ'],
      dealBreakers: ['رفتارهای نمایشی در فضای مجازی', 'عدم استقلال رای'],
      corePriorities: ['استقلال مالی', 'توسعه فردی', 'خانواده‌دوست'],
    },
    files: [],
  },
  {
    id: 'app_8472',
    fileCode: 'PR-8472#',
    firstName: 'مریم',
    lastName: 'احمدی (ا.)',
    gender: 'female',
    birthYear: 1370,
    birthDate: '۱۳۷۰/۱۱/۱۰',
    age: 32,
    city: 'تهران',
    province: 'تهران',
    address: 'تهران، امیرآباد شمالی',
    phone: '۰۹۱۲-۴۴۴-۵۵۶۶',
    nationalId: '۰۰۳۴۵۶۷۸۹۱',
    status: 'active',
    registrationDate: '۱۴۰۲/۰۷/۱۰',
    lastUpdate: 'امروز، ۱۰:۳۰',
    isVip: false,
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
    counselorId: 'user_counselor',
    counselorName: 'دکتر رمضانی',
    personalInfo: {
      height: 165,
      weight: 58,
      skinTone: 'روشن',
      healthStatus: 'سالم',
      militaryService: 'na',
      maritalHistory: 'single',
      hasChildren: false,
      childrenCount: 0,
      housingStatus: 'living_with_family',
    },
    familyInfo: {
      fatherLiving: true,
      fatherAge: 64,
      fatherJob: 'کارمند بازنشسته دادگستری',
      motherLiving: true,
      motherAge: 59,
      motherJob: 'خانه‌دار',
      siblingsCount: 2,
      siblingsOverview: '۲ برادر',
      familyCultureType: 'traditional',
      economicLevel: 'middle',
      counselorFamilyNotes: 'خانواده مذهبی، معتقد به حریم و چارچوب‌های سنتی.',
    },
    educationJob: {
      educationLevel: 'master',
      educationLevelFa: 'کارشناسی ارشد مهندسی صنایع',
      fieldOfStudy: 'مدیریت پروژه',
      university: 'دانشگاه علم و صنعت',
      occupation: 'مهندس نرم‌افزار و تحلیلگر سیستم',
      jobTitle: 'مهندس نرم‌افزار',
      organizationType: 'private',
      monthlyIncomeRange: '۴۰ تا ۵۵ میلیون تومان',
      financialIndependence: true,
      hasPersonalCar: true,
    },
    lifestyle: {
      smoking: false,
      exerciseLevel: 'regular',
      leisureActivities: ['ورزش پیلاتس', 'مطالعه', 'آشپزی'],
      travelInterest: 'moderate',
      socialMediaUsage: 'minimal',
    },
    religionValues: {
      religiousCommitment: 'high',
      religiousCommitmentFa: 'پایبند به احکام دینی و چادر',
      prayerCommitment: 'strict',
      hijabPreference: 'chador_complete',
      hijabPreferenceFa: 'چادر سنتی / دانشجویی مشکی',
      pilgrimageInterest: true,
      corePrinciples: ['وفاداری', 'احترام به بزرگترها', 'معنویت در خانه'],
    },
    personality: {
      mbti: 'ISFJ',
      mbtiTitleFa: 'مدافع و حامی صبور',
      attachmentStyle: 'ایمن',
      bigFive: {
        conscientiousness: 89,
        extraversion: 35,
        agreeableness: 86,
        neuroticism: 28,
        openness: 60,
      },
      keyTraits: ['مهربان', 'فداکار', 'منظم', 'دقیق'],
      counselorImpression: 'بسیار باوقار، متعهد به کانون خانواده و دارای مهارت‌های بالای خانه‌داری و عاطفی.',
    },
    marriagePreferences: {
      ageMin: 31,
      ageMax: 37,
      heightMin: 175,
      heightMax: 188,
      acceptableCities: ['تهران', 'قم'],
      minEducation: 'کارشناسی ارشد',
      acceptableMaritalHistory: ['single'],
      religiousExpectations: 'اهل نماز و مقید به روزه و حلال و حرام',
      financialExpectations: 'توانایی تامین مسکن و معیشت آبرومند',
      preferredMbtiList: ['ESTJ', 'ESFJ', 'ISTJ'],
      dealBreakers: ['بی‌احترامی به مقدسات', 'سیگار و قلیان'],
      corePriorities: ['اخلاق اسلامی', 'شغل شرافتمندانه', 'صداقت'],
    },
    files: [],
  },
  {
    id: 'app_8471',
    fileCode: 'PR-8471#',
    firstName: 'علی',
    lastName: 'رحمانی (ر.)',
    gender: 'male',
    birthYear: 1366,
    birthDate: '۱۳۶۶/۰۲/۱۴',
    age: 36,
    city: 'تهران',
    province: 'تهران',
    address: 'تهران، ستارخان',
    phone: '۰۹۱۲-۵۵۵-۶۶۷۷',
    nationalId: '۰۰۴۵۶۷۸۹۰۲',
    status: 'pending',
    registrationDate: '۱۴۰۲/۰۸/۲۵',
    lastUpdate: 'دیروز',
    isVip: false,
    photoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&auto=format&fit=crop&q=80',
    counselorId: 'user_counselor',
    counselorName: 'دکتر رمضانی',
    personalInfo: {
      height: 177,
      weight: 79,
      skinTone: 'گندمی',
      healthStatus: 'سالم',
      militaryService: 'completed',
      maritalHistory: 'single',
      hasChildren: false,
      childrenCount: 0,
      housingStatus: 'owner',
    },
    familyInfo: {
      fatherLiving: false,
      motherLiving: true,
      motherAge: 68,
      motherJob: 'خانه‌دار',
      siblingsCount: 3,
      siblingsOverview: '۲ برادر و ۱ خواهر (همگی متأهل)',
      familyCultureType: 'traditional',
      economicLevel: 'middle',
      counselorFamilyNotes: 'فرزند ارشد خانواده، متعهد و حامی مادر.',
    },
    educationJob: {
      educationLevel: 'phd',
      educationLevelFa: 'دکتری عمومی پزشکی',
      fieldOfStudy: 'پزشکی عمومی',
      university: 'دانشگاه علوم پزشکی شهید بهشتی',
      occupation: 'پزشک در درمانگاه و بیمارستان',
      jobTitle: 'پزشک عمومی',
      organizationType: 'government',
      monthlyIncomeRange: '۵۰ تا ۷۰ میلیون تومان',
      financialIndependence: true,
      hasPersonalCar: true,
    },
    lifestyle: {
      smoking: false,
      exerciseLevel: 'occasional',
      leisureActivities: ['مطالعه مقالات پزشکی', 'دیدار با اقوام', 'ورزش صبحگاهی'],
      travelInterest: 'moderate',
      socialMediaUsage: 'minimal',
    },
    religionValues: {
      religiousCommitment: 'high',
      religiousCommitmentFa: 'معتقد و پایبند به شئونات مذهبی',
      prayerCommitment: 'strict',
      hijabPreference: 'chador_complete',
      hijabPreferenceFa: 'چادر کامل',
      pilgrimageInterest: true,
      corePrinciples: ['خدمت به مردم', 'تقوا', 'صله رحم'],
    },
    personality: {
      mbti: 'ISTJ',
      mbtiTitleFa: 'تدارکاتچی و قانون‌گرا',
      attachmentStyle: 'ایمن',
      bigFive: {
        conscientiousness: 94,
        extraversion: 30,
        agreeableness: 72,
        neuroticism: 20,
        openness: 55,
      },
      keyTraits: ['مسئول', 'منضبط', 'صادق', 'عمل‌گرا'],
      counselorImpression: 'شخصیتی بسیار ثابت‌قدم و باوقار، نیازمند همسری با درک شیفت‌های درمانی.',
    },
    marriagePreferences: {
      ageMin: 27,
      ageMax: 33,
      heightMin: 160,
      heightMax: 172,
      acceptableCities: ['تهران'],
      minEducation: 'کارشناسی',
      acceptableMaritalHistory: ['single'],
      religiousExpectations: 'محجبه کامل، اهل نماز و اخلاق',
      financialExpectations: 'همراهی و مدیریت اقتصادی خانه',
      preferredMbtiList: ['ISFJ', 'ESFJ', 'ESTJ'],
      dealBreakers: ['عدم سازگاری با خانواده', 'توقعات خارج از عرف'],
      corePriorities: ['پایبندی مذهبی', 'سادگی و قناعت', 'آرامش محیط خانه'],
    },
    files: [],
  },
  {
    id: 'app_8465',
    fileCode: 'PR-8465#',
    firstName: 'زهرا',
    lastName: 'صادقی (ص.)',
    gender: 'female',
    birthYear: 1373,
    birthDate: '۱۳۷۳/۰۶/۰۵',
    age: 29,
    city: 'تهران',
    province: 'تهران',
    address: 'تهران، نارمک',
    phone: '۰۹۱۲-۷۷۷-۸۸۹۹',
    nationalId: '۰۰۵۶۷۸۹۰۱۲',
    status: 'introduced',
    registrationDate: '۱۴۰۲/۰۶/۲۰',
    lastUpdate: '۲ روز پیش',
    isVip: false,
    photoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=300&auto=format&fit=crop&q=80',
    counselorId: 'user_counselor',
    counselorName: 'دکتر رمضانی',
    personalInfo: {
      height: 164,
      weight: 56,
      skinTone: 'گندمی روشن',
      healthStatus: 'سالم',
      militaryService: 'na',
      maritalHistory: 'single',
      hasChildren: false,
      childrenCount: 0,
      housingStatus: 'living_with_family',
    },
    familyInfo: {
      fatherLiving: true,
      fatherAge: 63,
      fatherJob: 'بازاری و معتمد محله',
      motherLiving: true,
      motherAge: 58,
      motherJob: 'خانه‌دار',
      siblingsCount: 2,
      siblingsOverview: '۱ برادر و ۱ خواهر',
      familyCultureType: 'traditional',
      economicLevel: 'middle',
      counselorFamilyNotes: 'خانواده اصیل و آبرومند.',
    },
    educationJob: {
      educationLevel: 'phd',
      educationLevelFa: 'دانشجوی دکتری ادبیات فارسی',
      fieldOfStudy: 'زبان و ادبیات فارسی',
      university: 'دانشگاه علامه طباطبایی',
      occupation: 'مدرس دانشگاه و پژوهشگر',
      jobTitle: 'مدرس دانشگاه',
      organizationType: 'academic',
      monthlyIncomeRange: '۳۰ تا ۴۵ میلیون تومان',
      financialIndependence: true,
      hasPersonalCar: true,
    },
    lifestyle: {
      smoking: false,
      exerciseLevel: 'regular',
      leisureActivities: ['شعرخوانی', 'مطالعه کتاب‌های تاریخی', 'سفرهای فرهنگی'],
      travelInterest: 'high',
      socialMediaUsage: 'moderate',
    },
    religionValues: {
      religiousCommitment: 'high',
      religiousCommitmentFa: 'معتقد به ارزش‌های دینی و پوشش چادر',
      prayerCommitment: 'strict',
      hijabPreference: 'chador_complete',
      hijabPreferenceFa: 'چادر ملی و موقر',
      pilgrimageInterest: true,
      corePrinciples: ['معنویت', 'صداقت', 'رشد اخلاقی'],
    },
    personality: {
      mbti: 'INFJ',
      mbtiTitleFa: 'حامی و آرمان‌گرا',
      attachmentStyle: 'ایمن',
      bigFive: {
        conscientiousness: 85,
        extraversion: 35,
        agreeableness: 90,
        neuroticism: 25,
        openness: 88,
      },
      keyTraits: ['صبور', 'بااحساس', 'کتابخوان', 'متفکر'],
      counselorImpression: 'روحیه‌ای عمیق، ادیب و آرام با ظرفیت عاطفی بسیار بالا.',
    },
    marriagePreferences: {
      ageMin: 30,
      ageMax: 37,
      heightMin: 175,
      heightMax: 188,
      acceptableCities: ['تهران', 'اصفهان', 'قم'],
      minEducation: 'کارشناسی ارشد',
      acceptableMaritalHistory: ['single'],
      religiousExpectations: 'همفکر در ارزش‌های معنوی و اخلاق‌مداری',
      financialExpectations: 'رزق حلال و تلاش برای پیشرفت زندگی',
      preferredMbtiList: ['ENFP', 'ENTP', 'INTJ', 'INFJ'],
      dealBreakers: ['دروغ', 'خشونت کلامی', 'لقمه شبهه‌ناک'],
      corePriorities: ['تناسب فکری', 'احترام به فرهنگ و هنر', 'صداقت'],
    },
    files: [],
  },
  {
    id: 'app_8490',
    fileCode: 'PR-8490#',
    firstName: 'محمد',
    lastName: 'کاظمی',
    gender: 'male',
    birthYear: 1369,
    birthDate: '۱۳۶۹/۰۱/۱۵',
    age: 34,
    city: 'اصفهان',
    province: 'اصفهان',
    address: 'اصفهان، خیابان نظر شرقی',
    phone: '۰۹۱۳-۱۲۳-۴۵۶۷',
    nationalId: '۱۲۸۹۰۱۲۳۴۵',
    status: 'active',
    registrationDate: '۱۴۰۲/۰۷/۱۵',
    lastUpdate: '۳ روز پیش',
    isVip: false,
    photoUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=300&auto=format&fit=crop&q=80',
    counselorId: 'user_counselor',
    counselorName: 'دکتر رمضانی',
    personalInfo: {
      height: 185,
      weight: 82,
      skinTone: 'گندمی',
      healthStatus: 'سالم',
      militaryService: 'completed',
      maritalHistory: 'single',
      hasChildren: false,
      childrenCount: 0,
      housingStatus: 'owner',
    },
    familyInfo: {
      fatherLiving: true,
      fatherAge: 67,
      fatherJob: 'بازرگان صنایع دستی',
      motherLiving: true,
      motherAge: 62,
      motherJob: 'خانه‌دار',
      siblingsCount: 3,
      siblingsOverview: '۲ خواهر و ۱ برادر',
      familyCultureType: 'traditional',
      economicLevel: 'high',
      counselorFamilyNotes: 'خانواده اصیل و سرشناس اصفهان.',
    },
    educationJob: {
      educationLevel: 'master',
      educationLevelFa: 'کارشناسی ارشد مدیریت بازرگانی',
      fieldOfStudy: 'مدیریت بازرگانی و تجارت الکترونیک',
      university: 'دانشگاه اصفهان',
      occupation: 'مدیر عامل شرکت صادرات صنایع دستی',
      jobTitle: 'مدیر عامل',
      organizationType: 'private',
      monthlyIncomeRange: '۸۰ تا ۱۲۰ میلیون تومان',
      financialIndependence: true,
      hasPersonalCar: true,
    },
    lifestyle: {
      smoking: false,
      exerciseLevel: 'regular',
      leisureActivities: ['سوارکاری', 'مسافرت به شهرهای تاریخی', 'ورزش تنیس'],
      travelInterest: 'high',
      socialMediaUsage: 'moderate',
    },
    religionValues: {
      religiousCommitment: 'moderate',
      religiousCommitmentFa: 'معتقد به اخلاق دینی و ادای واجبات',
      prayerCommitment: 'regular',
      hijabPreference: 'manteau_modest',
      hijabPreferenceFa: 'پوشش باوقار و شیک',
      pilgrimageInterest: true,
      corePrinciples: ['درستکاری مالی', 'خانواده‌محوری', 'احترام متقابل'],
    },
    personality: {
      mbti: 'ENTJ',
      mbtiTitleFa: 'فرمانده و رهبر قاطع',
      attachmentStyle: 'ایمن',
      bigFive: {
        conscientiousness: 92,
        extraversion: 75,
        agreeableness: 60,
        neuroticism: 18,
        openness: 78,
      },
      keyTraits: ['کاریزماتیک', 'پرتلاش', 'با اراده', 'مدیر'],
      counselorImpression: 'شخصیتی بسیار موفق، خوش‌برخورد با اهداف بلندمدت روشن برای تشکیل خانواده.',
    },
    marriagePreferences: {
      ageMin: 25,
      ageMax: 31,
      heightMin: 165,
      heightMax: 178,
      acceptableCities: ['اصفهان', 'تهران', 'شیراز'],
      minEducation: 'کارشناسی',
      acceptableMaritalHistory: ['single'],
      religiousExpectations: 'همفکر در ارزش‌ها و پایبند به حریم خانواده',
      financialExpectations: 'درک متقابل در سبک زندگی شایسته',
      preferredMbtiList: ['INFP', 'INTP', 'ENFP', 'ISFP'],
      dealBreakers: ['اسراف و تجمل‌زدگی بیمارگونه', 'عدم انگیزه برای تعالی خانوادگی'],
      corePriorities: ['اصالت خانوادگی', 'هوش اجتماعی بالا', 'صداقت'],
    },
    files: [],
  },
  {
    id: 'app_8492',
    fileCode: 'PR-8492#',
    firstName: 'نیلوفر',
    lastName: 'مرادی',
    gender: 'female',
    birthYear: 1372,
    birthDate: '۱۳۷۲/۰۹/۱۴',
    age: 30,
    city: 'تهران',
    province: 'تهران',
    address: 'تهران، ولنجک',
    phone: '۰۹۱۲-۳۳۳-۷۷۸۸',
    nationalId: '۰۰۶۷۸۹۰۱۲۳',
    status: 'active',
    registrationDate: '۱۴۰۲/۰۸/۰۱',
    lastUpdate: '۴ روز پیش',
    isVip: true,
    photoUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=300&auto=format&fit=crop&q=80',
    counselorId: 'user_counselor',
    counselorName: 'دکتر رمضانی',
    personalInfo: {
      height: 170,
      weight: 60,
      skinTone: 'سفید',
      healthStatus: 'سالم',
      militaryService: 'na',
      maritalHistory: 'single',
      hasChildren: false,
      childrenCount: 0,
      housingStatus: 'living_with_family',
    },
    familyInfo: {
      fatherLiving: true,
      fatherAge: 65,
      fatherJob: 'مهندس مشاور',
      motherLiving: true,
      motherAge: 60,
      motherJob: 'روانشناس بالینی',
      siblingsCount: 1,
      siblingsOverview: '۱ برادر (مقیم خارج از کشور)',
      familyCultureType: 'modern',
      economicLevel: 'high',
      counselorFamilyNotes: 'خانواده فرهیخته با فضای گفتگوی باز و علمی.',
    },
    educationJob: {
      educationLevel: 'master',
      educationLevelFa: 'کارشناسی ارشد مدیریت فناوری اطلاعات',
      fieldOfStudy: 'سیستم‌های اطلاعاتی',
      university: 'دانشگاه شهید بهشتی',
      occupation: 'کارشناس داده و هوش تجاری',
      jobTitle: 'کارشناس هوش تجاری',
      organizationType: 'private',
      monthlyIncomeRange: '۴۵ تا ۶۰ میلیون تومان',
      financialIndependence: true,
      hasPersonalCar: true,
    },
    lifestyle: {
      smoking: false,
      exerciseLevel: 'regular',
      leisureActivities: ['یوگا', 'مطالعه رمان‌های کلاسیک', 'یادگیری زبان آلمانی'],
      travelInterest: 'high',
      socialMediaUsage: 'moderate',
    },
    religionValues: {
      religiousCommitment: 'cultural',
      religiousCommitmentFa: 'معتقد به اخلاقیات انسانی و معنویت آزاد',
      prayerCommitment: 'occasional',
      hijabPreference: 'manteau_casual',
      hijabPreferenceFa: 'پوشش مانتویی عرفی و آزاد',
      pilgrimageInterest: false,
      corePrinciples: ['برابری و احترام متقابل', 'آزادی اندیشه', 'رشد فردی'],
    },
    personality: {
      mbti: 'INFP',
      mbtiTitleFa: 'میانجی و آرمان‌خواه',
      attachmentStyle: 'ایمن',
      bigFive: {
        conscientiousness: 68,
        extraversion: 45,
        agreeableness: 88,
        neuroticism: 30,
        openness: 90,
      },
      keyTraits: ['رویاپرداز', 'همدل', 'صبور', 'آرامش‌بخش'],
      counselorImpression: 'روحیه هنرمندانه و منعطف دارد که با افراد مقتدر و حمایت‌گر سازگاری مطلوبی می‌سازد.',
    },
    marriagePreferences: {
      ageMin: 30,
      ageMax: 38,
      heightMin: 178,
      heightMax: 192,
      acceptableCities: ['تهران'],
      minEducation: 'کارشناسی ارشد',
      acceptableMaritalHistory: ['single'],
      religiousExpectations: 'روشن‌بین، بدون تحمیل عقیده',
      financialExpectations: 'رفاه نسبی و تامین مسکن مناسب',
      preferredMbtiList: ['ENTJ', 'ENFJ', 'INTJ'],
      dealBreakers: ['نگرش‌های پدرسالارانه سنتی', 'تحکم و کنترل‌گری'],
      corePriorities: ['درک دوجانبه', 'حمایت عاطفی', 'احترام به استقلال شغلی'],
    },
    files: [],
  },
];

export const INITIAL_APPLICANTS: Applicant[] = RAW_APPLICANTS.map(buildApplicant);

export const INITIAL_INTRODUCTIONS: Introduction[] = [
  {
    id: 'intro_101',
    introCode: 'INT-9401',
    maleApplicantId: 'app_49821',
    maleApplicantName: 'علیرضا محمدی',
    maleFileCode: '۴۹۸۲۱#',
    maleAge: 32,
    maleJob: 'مدیر محصول',
    femaleApplicantId: 'app_519',
    femaleApplicantName: 'سارا محمدی (م.)',
    femaleFileCode: '۵۱۹#',
    femaleAge: 28,
    femaleJob: 'معمار داخلی',
    createdDate: '۱۴۰۲/۰۹/۱۰',
    compatibilityScore: 85,
    status: 'meeting',
    statusFa: 'جلسه معارفه حضوری',
    stageName: 'جلسه دوم گفتگو در اتاق مشاوره ۲',
    meetingDate: '۱۴۰۲/۰۹/۲۴ - ساعت ۱۶:۰۰',
    meetingLocation: 'مرکز الزهرا - اتاق گفتگوی شماره ۲',
    counselorId: 'user_counselor',
    counselorName: 'دکتر رمضانی',
    notes: 'هر دو مراجع اشتیاق بالایی برای گفتگو نشان دادند. جلسه اول مثبت بوده و سوالات اقتصادی و اهداف مشترک در جلسه دوم بررسی می‌شود.',
    timeline: [
      { date: '۱۴۰۲/۰۹/۱۰', title: 'پیشنهاد هوشمند توسط سیستم', description: 'تطابق با امتیاز ۸۵٪ استخراج گردید.', actor: 'سیستم تطبیق هوشمند' },
      { date: '۱۴۰۲/۰۹/۱۲', title: 'تماس و اخذ موافقت اولیه', description: 'خلاصه پرونده بدون اطلاعات تماس برای طرفین ارسال و تایید شد.', actor: 'خانم ناصری (کارشناس)' },
      { date: '۱۴۰۲/۰۹/۱۸', title: 'جلسه حضوری اول', description: 'جلسه ۴۵ دقیقه‌ای با نظارت مشاور برگزار شد. بازخورد اولیه بسیار مثبت بود.', actor: 'دکتر رمضانی (مشاور)' },
    ],
  },
  {
    id: 'intro_102',
    introCode: 'INT-9388',
    maleApplicantId: 'app_482',
    maleApplicantName: 'امیرحسین رضایی',
    maleFileCode: '۴۸۲#',
    maleAge: 32,
    maleJob: 'مهندس نرم‌افزار',
    femaleApplicantId: 'app_519',
    femaleApplicantName: 'سارا محمدی (م.)',
    femaleFileCode: '۵۱۹#',
    femaleAge: 28,
    femaleJob: 'معمار داخلی',
    createdDate: '۱۴۰۲/۰۸/۲۰',
    compatibilityScore: 85,
    status: 'contacted',
    statusFa: 'تماس اولیه و بررسی خانواده‌ها',
    stageName: 'در انتظار بازخورد خانواده دختر',
    meetingDate: '۱۴۰۲/۰۹/۲۸ (پیشنهادی)',
    counselorId: 'user_counselor',
    counselorName: 'دکتر رمضانی',
    notes: 'آقای مهندس رضایی رزومه و شرایط کلی را پذیرفته‌اند.',
    timeline: [
      { date: '۱۴۰۲/۰۸/۲۰', title: 'ثبت در سامانه معرفی', description: 'تایید توسط مدیر تطبیق مرکز', actor: 'کارشناس پذیرش' },
      { date: '۱۴۰۲/۰۸/۲۲', title: 'ارسال خلاصه بی‌نام به خانم سارا م.', description: 'در حال بررسی توسط خانواده', actor: 'خانم ناصری' },
    ],
  },
  {
    id: 'intro_103',
    introCode: 'INT-9350',
    maleApplicantId: 'app_8471',
    maleApplicantName: 'دکتر علی رحمانی',
    maleFileCode: 'PR-8471#',
    maleAge: 36,
    maleJob: 'پزشک عمومی',
    femaleApplicantId: 'app_8472',
    femaleApplicantName: 'مریم احمدی',
    femaleFileCode: 'PR-8472#',
    femaleAge: 32,
    femaleJob: 'مهندس نرم‌افزار',
    createdDate: '۱۴۰۲/۰۷/۲۸',
    compatibilityScore: 92,
    status: 'successful',
    statusFa: 'موفق (عقد رسمی / پیوند)',
    stageName: 'پرونده پیوند موفق با اهدای یادبود مرکز',
    counselorId: 'user_counselor',
    counselorName: 'دکتر رمضانی',
    notes: 'تطابق بسیار عالی مذهبی و خانوادگی. مراسم عقد با حضور نماینده مرکز برگزار شد.',
    timeline: [
      { date: '۱۴۰۲/۰۷/۲۸', title: 'تشکیل پرونده معرفی', description: 'همسویی ۹۲ درصدی در ملاک‌های اعتقادی و سبک زندگی', actor: 'سیستم تطبیق' },
      { date: '۱۴۰۲/۰۸/۰۵', title: 'جلسات مشاوره پیش از ازدواج (۳ جلسه)', description: 'تست‌های سازگاری و حل تعارض با نمره عالی طی شد.', actor: 'دکتر رمضانی' },
      { date: '۱۴۰۲/۰۸/۳۰', title: 'عقد دائم رسمی', description: 'ثبت پیوند در تالار پیوند مرکز', actor: 'مدیریت مرکز' },
    ],
  },
  {
    id: 'intro_104',
    introCode: 'INT-9290',
    maleApplicantId: 'app_49821',
    maleApplicantName: 'علیرضا محمدی',
    maleFileCode: '۴۹۸۲۱#',
    maleAge: 32,
    maleJob: 'مدیر محصول',
    femaleApplicantId: 'app_8492',
    femaleApplicantName: 'نیلوفر مرادی',
    femaleFileCode: 'PR-8492#',
    femaleAge: 30,
    femaleJob: 'کارشناس هوش تجاری',
    createdDate: '۱۴۰۲/۰۸/۲۸',
    compatibilityScore: 68,
    status: 'rejected',
    statusFa: 'عدم توافق (بایگانی مورد)',
    stageName: 'پایان فرایند پس از جلسه دوم',
    rejectionReason: 'تفاوت در دیدگاه‌های اقتصادی و میزان پایبندی به مناسک سنتی',
    counselorId: 'user_counselor',
    counselorName: 'دکتر رمضانی',
    notes: 'پس از جلسه دوم مشاوره، طرفین با توافق دوجانبه تصمیم به عدم ادامه فرآیند گرفتند.',
    timeline: [
      { date: '۱۴۰۲/۰۸/۲۸', title: 'جلسه معارفه اولیه', description: 'برگزاری جلسه حضوری', actor: 'دکتر رمضانی' },
      { date: '۱۴۰۲/۰۹/۰۲', title: 'ثبت نتیجه عدم توافق', description: 'علت ثبت شده: تفاوت در دیدگاه‌های اقتصادی و نگرش‌های فرهنگی', actor: 'کارشناس پرونده' },
    ],
  },
];

export const INITIAL_COUNSELING_SESSIONS: CounselingSession[] = [
  {
    id: 'sess_1',
    applicantId: 'app_49821',
    applicantName: 'علیرضا محمدی',
    applicantFileCode: '۴۹۸۲۱#',
    sessionNumber: 3,
    title: 'جلسه مشاوره سوم (ارزیابی پیشرفت و تحلیل معرفی)',
    sessionDate: '۱۴۰۲/۰۹/۱۲',
    sessionTime: '۱۴:۳۰',
    roomNumber: 'اتاق شماره ۲',
    counselorId: 'user_counselor',
    counselorName: 'دکتر رمضانی',
    topics: ['بررسی بازخورد مورد قبلی', 'تعدیل معیارهای آرمانی', 'مهارت‌های گوش‌دادن فعال'],
    summary: 'مراجع در بیان احساسات خود نسبت به معرفی قبلی پیشرفت نشان داده است. انتظارات ایشان واقع‌بینانه‌تر شده و آماده برای بررسی کیس‌های جدید با تمرکز بر اشتراکات فکری هستند.',
    privateNotes: 'مراجع تمایل به کمال‌گرایی در انتخاب همسر دارد که در جلسه امروز به آن واقف شد. پذیرش تفاوت‌های فردی تا ۸۰٪ ارتقا یافته است. آماده معارفه جدید با خانم‌های پرانرژی و همدل (ENFP).',
    readinessScore: 88,
    homework: 'تکمیل کاربرگ خطاهای شناختی در انتخاب شریک زندگی',
    status: 'completed',
  },
  {
    id: 'sess_2',
    applicantId: 'app_519',
    applicantName: 'سارا محمدی (م.)',
    applicantFileCode: '۵۱۹#',
    sessionNumber: 2,
    title: 'جلسه مشاوره فردی و بررسی سبک دلبستگی',
    sessionDate: '۱۴۰۲/۰۹/۰۸',
    sessionTime: '۱۶:۰۰',
    roomNumber: 'اتاق شماره ۱',
    counselorId: 'user_counselor',
    counselorName: 'دکتر رمضانی',
    topics: ['سبک دلبستگی ایمن', 'مرزهای ارتباطی با خانواده همسر', 'مدیریت تعارض'],
    summary: 'خانم مهندس سارا م. از هوش هیجانی بسیار خوبی برخوردارند. انگیزه بالا برای ازدواج بهنگام و موفق دارند.',
    privateNotes: 'مراجع از ثبات رفتاری عالی برخوردار است و در خانواده‌ای صمیمی رشد یافته. پذیرش خوبی نسبت به نقش همسری و مادرانه دارد.',
    readinessScore: 92,
    status: 'completed',
  },
  {
    id: 'sess_3',
    applicantId: 'app_49821',
    applicantName: 'علیرضا محمدی و سارا محمدی',
    applicantFileCode: '۴۹۸۲۱# و ۵۱۹#',
    sessionNumber: 4,
    title: 'جلسه مشاوره مشترک زوجین (ارزیابی تطابق پیش از عقد)',
    sessionDate: '۱۴۰۲/۰۹/۲۴',
    sessionTime: '۱۵:۰۰',
    roomNumber: 'اتاق کنفرانس زوجین',
    counselorId: 'user_counselor',
    counselorName: 'دکتر رمضانی',
    topics: ['توافق در مسائل مالی و مسکن', 'همسویی اهداف ۵ ساله', 'حل تعارض'],
    summary: 'جلسه هماهنگ شده و دعوت‌نامه‌ها برای طرفین ارسال گردید.',
    privateNotes: 'جلسه نهایی جهت سنجش تعهد طرفین پیش از مراسم رسمی.',
    readinessScore: 90,
    status: 'scheduled',
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task_1',
    title: 'بررسی پرونده آقای رضایی',
    description: 'تکمیل فرم‌های اولیه ارزیابی پیش از جلسه عصر.',
    priority: 'urgent',
    isDone: false,
    dueDate: 'امروز',
    dueTime: '۱۴:۰۰',
    assignedRole: 'counselor',
    assignedUserName: 'دکتر علیرضا رمضانی',
    relatedApplicantId: 'app_482',
    relatedApplicantName: 'امیرحسین رضایی',
    relatedApplicantPhone: '۰۹۱۲-۱۱۱-۲۲۳۳',
    type: 'review',
  },
  {
    id: 'task_2',
    title: 'ارسال پیامک یادآوری به لیست انتظار',
    description: 'برای مراجعین ثبت نام شده در هفته گذشته.',
    priority: 'medium',
    isDone: false,
    dueDate: 'امروز',
    dueTime: '۱۶:۰۰',
    assignedRole: 'employee',
    assignedUserName: 'خانم ناصری',
    type: 'sms',
  },
  {
    id: 'task_3',
    title: 'بروزرسانی وضعیت مالی مراجعین',
    description: 'بررسی پرداختی‌های مربوط به مشاوره‌های روز گذشته.',
    priority: 'low',
    isDone: false,
    dueDate: 'امروز',
    dueTime: '۱۷:۳۰',
    assignedRole: 'internal_manager',
    assignedUserName: 'خانم دکتر حسینی',
    type: 'finance',
  },
  {
    id: 'task_4',
    title: 'تماس پیگیری با مریم محمدی',
    description: 'پیگیری بازخورد جلسه دوم و بررسی زمانبندی جلسه مشترک.',
    priority: 'urgent',
    isDone: false,
    dueDate: 'امروز',
    dueTime: '۱۱:۰۰',
    assignedRole: 'employee',
    assignedUserName: 'خانم ناصری',
    relatedApplicantId: 'app_519',
    relatedApplicantName: 'مریم محمدی',
    relatedApplicantPhone: '۰۹۱۲-۹۸۷-۶۵۴۳',
    type: 'call',
  },
  {
    id: 'task_5',
    title: 'تماس ارزیابی اولیه معرفی با علی کریمی',
    description: 'ارزیابی اولیه معرفی پرونده کد #PR-8471 و دریافت تاییدیه حضور.',
    priority: 'medium',
    isDone: false,
    dueDate: 'امروز',
    dueTime: '۱۲:۳۰',
    assignedRole: 'employee',
    assignedUserName: 'خانم ناصری',
    relatedApplicantId: 'app_8471',
    relatedApplicantName: 'علی کریمی',
    relatedApplicantPhone: '۰۹۱۲-۵۵۵-۶۶۷۷',
    type: 'call',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log_1',
    timestamp: '۱۴۰۲/۰۹/۱۲ - ۱۰:۳۰',
    userId: 'user_counselor',
    userName: 'دکتر علیرضا رمضانی',
    userRole: 'counselor',
    action: 'ثبت یادداشت محرمانه مشاوره',
    targetEntity: 'Applicant',
    targetId: '۴۹۸۲۱#',
    details: 'جلسه سوم مراجع علیرضا محمدی با موفقیت ثبت شد.',
  },
  {
    id: 'log_2',
    timestamp: '۱۴۰۲/۰۹/۱۰ - ۱۱:۱۵',
    userId: 'user_employee',
    userName: 'خانم سمیه ناصری',
    userRole: 'employee',
    action: 'ایجاد پرونده معرفی',
    targetEntity: 'Introduction',
    targetId: 'INT-9401',
    details: 'تطبیق پرونده ۴۹۸۲۱# و ۵۱۹# به مرحله جلسه حضوری ارتقا یافت.',
  },
  {
    id: 'log_3',
    timestamp: '۱۴۰۲/۰۹/۰۸ - ۰۹:۰۰',
    userId: 'user_manager',
    userName: 'خانم دکتر حسینی',
    userRole: 'internal_manager',
    action: 'تایید ارزیابی اولیه مراجع',
    targetEntity: 'Applicant',
    targetId: '۵۱۹#',
    details: 'مدارک و آزمون روانشناختی سارا م. تایید و پرونده فعال شد.',
  },
];
